# Generated by Django 4.2.7 on 2025-10-03 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobapplication",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="jobposting",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="leaverequest",
            options={"ordering": ["-created_at"]},
        ),
    ]
