# Generated by Django 4.2.7 on 2025-10-03 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_jobapplication_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ["first_name", "last_name"]},
        ),
    ]
