# Generated by Django 4.2.7 on 2025-11-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_employee_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="department",
            name="abbreviation",
            field=models.CharField(default="DEPT", max_length=10),
        ),
        migrations.AddField(
            model_name="employee",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("full-time", "Full-time"),
                    ("part-time", "Part-time"),
                    ("contract", "Contract"),
                ],
                default="full-time",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="role",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
